Dev
BenAB98/Movie-App-Vue pull request #1
Opened 2023-07-07 16:40 UTC by BenAB98

2023-07-08 11:40 UTC, amRashidi requested changes

2023-07-08 11:40 UTC, amRashidi commented on src/App.vue
> +// import Edit from './pages/Edit.vue';
remove comments

2023-07-08 11:40 UTC, amRashidi commented on src/components/ButtonPrimary.vue
> +<style scoped></style>
remove empty style tag

2023-07-08 11:40 UTC, amRashidi commented on src/components/FooterComponent.vue
> +        <a href="#" rel="nofallow" class="block w-fit hover:text-ogangeLink transition-all"
use v-for

2023-07-08 11:40 UTC, amRashidi commented on src/components/FooterComponent.vue
> +          >Pinterest</a
same

2023-07-08 11:40 UTC, amRashidi commented on src/components/HeaderComponent.vue
> +          <a
vfor
href???

2023-07-08 11:40 UTC, amRashidi commented on src/components/MainComponent.vue
> +fetchApi('https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=3')
base url

2023-07-08 11:40 UTC, amRashidi commented on src/components/MainComponent.vue
> +      <skeleton v-if="!moviesList.length" height="100vh" width="100%" borderRadius="12px" />
wrong condition

2023-07-08 11:40 UTC, amRashidi commented on src/components/MainComponent.vue
> +        :src="`https://image.tmdb.org/t/p/w500${movie.poster_path}`"
base url for images

2023-07-08 11:40 UTC, amRashidi commented on src/fetchAPI.js
> +      Authorization: `Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwM2E1YTEzZTk4NTk4NDcyNTRjYWQ5M2E5Nzg2MjEzYyIsInN1YiI6IjY0NzFiMmE0YmUyZDQ5MDBiZjlkNWFhMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Xu
avoid hardcoding your token!!
do this with env

2023-07-08 11:40 UTC, amRashidi commented on src/layout/ScrollingFree.vue
> +fetchApi('https://api.themoviedb.org/3/movie/popular?language=en-US&page=2')
base url

2023-07-08 11:40 UTC, amRashidi commented on src/layout/ScrollingPapulars.vue
> +fetchApi('https://api.themoviedb.org/3/movie/popular?language=en-US&page=1')
base url

2023-07-08 11:40 UTC, amRashidi commented on src/pages/Edit.vue
> +        <span class="">
v-for

2023-07-08 11:40 UTC, amRashidi commented on src/pages/Login.vue
> +        <a href="signup.html" class="text-grayLight hover:text-ogangeLink transition-all w-fit"
href!!

2023-07-08 11:40 UTC, amRashidi commented on src/pages/MainPage.vue
> +import MainComponent from '../components/MainComponent.vue'
global address

2023-07-08 11:40 UTC, amRashidi commented on src/pages/MovieDetailsPage.vue
> +fetchApi('https://api.themoviedb.org/3/configuration')
base url

2023-07-08 11:40 UTC, amRashidi commented on src/pages/SignUp.vue
> +import FormComponent from '../components/FormComponent.vue'
global address url

2023-07-16 19:11 UTC, BenAB98 commented
@amRashidi Changes have been made as requested

2023-07-17 15:03 UTC, amRashidi approved these changes

2023-07-17 15:03 UTC, merged